# generated by configure / remove this line to disable regeneration
prefix="/usr/local"
exec_prefix="${prefix}"
bindir="${exec_prefix}/bin"
libdir="/root/pluto/openscop/.libs"
datarootdir="${prefix}/share"
datadir="${datarootdir}"
sysconfdir="${prefix}/etc"
includedir="/root/pluto/openscop/./include"
package="osl"
suffix=""

for option; do case "$option" in --list-all|--name) echo  "osl"
;; --help) pkg-config --help ; echo Buildscript Of "osl Library"
;; --modversion|--version) echo "0.9.5"
;; --requires) echo : ""
;; --libs) echo -L${libdir} "" "-losl -lgmp -lgmp"
       :
;; --cflags) echo -I${includedir} "-DOSL_GMP_IS_HERE"
       :
;; --variable=*) eval echo '$'`echo $option | sed -e 's/.*=//'`
;; --uninstalled) exit 0 
;; *) ;; esac done
